name: Check PR Head SHA Value

on: pull_request

jobs:
  check-pr-head-sha:
    runs-on: ubuntu-latest
    steps:
    - name: GET PR Head
      env:
        PR_HEAD_SHA_VALUE: ${{ github.event.pull_request.head.sha }}
      run: |
        echo This PRs Head SHA Value is $PR_HEAD_SHA_VALUE
